<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 3.2.1 (Python 3.6.9 on linux)" generated="20200602 13:37:31.066" rpa="false">
<suite id="s1" name="Test Pets Api" source="/home/sadovsky/PycharmProjects/testStore/tests/test_pets_api.robot">
<test id="s1-t1" name="Test pets endpointes">
<kw name="create pets via api">
<kw name="add pets to store">
<msg timestamp="20200602 13:37:31.122" level="FAIL">No keyword with name 'add pets to store' found.</msg>
<status status="FAIL" starttime="20200602 13:37:31.122" endtime="20200602 13:37:31.122"></status>
</kw>
<status status="FAIL" starttime="20200602 13:37:31.121" endtime="20200602 13:37:31.122"></status>
</kw>
<tags>
<tag>DEBUG</tag>
</tags>
<status status="FAIL" starttime="20200602 13:37:31.121" endtime="20200602 13:37:31.123" critical="yes">No keyword with name 'add pets to store' found.</status>
</test>
<status status="FAIL" starttime="20200602 13:37:31.067" endtime="20200602 13:37:31.123"></status>
</suite>
<statistics>
<total>
<stat pass="0" fail="1">Critical Tests</stat>
<stat pass="0" fail="1">All Tests</stat>
</total>
<tag>
<stat pass="0" fail="1">DEBUG</stat>
</tag>
<suite>
<stat pass="0" fail="1" id="s1" name="Test Pets Api">Test Pets Api</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20200602 13:37:31.120" level="ERROR">Error in file '/home/sadovsky/PycharmProjects/testStore/tests/test_pets_api.robot' on line 7: Importing test library '/home/sadovsky/PycharmProjects/testStore/storeLibrary/PetsLibrary.py' failed: ModuleNotFoundError: No module named 'helpers'
Traceback (most recent call last):
  File "/home/sadovsky/PycharmProjects/testStore/storeLibrary/PetsLibrary.py", line 3, in &lt;module&gt;
    from helpers.ApiHelper import ApiHelper
PYTHONPATH:
  /home/sadovsky/PycharmProjects/testStore/venv/bin
  /usr/lib/python36.zip
  /usr/lib/python3.6
  /usr/lib/python3.6/lib-dynload
  /home/sadovsky/PycharmProjects/testStore/venv/lib/python3.6/site-packages</msg>
</errors>
</robot>
